# Generated by Django 3.1.6 on 2021-02-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
                ('starting_price', models.IntegerField()),
                ('current_price', models.IntegerField()),
                ('image_url', models.CharField(max_length=256)),
                ('category_id', models.IntegerField()),
                ('status', models.CharField(max_length=64)),
            ],
        ),
    ]
