# Generated by Django 3.1.6 on 2021-02-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210213_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='current_price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='starting_price',
            field=models.PositiveIntegerField(),
        ),
    ]
