# Generated by Django 3.1.6 on 2021-02-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210213_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='category_id',
        ),
        migrations.AddField(
            model_name='listing',
            name='category_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
