# Generated by Django 3.1.6 on 2021-02-15 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210213_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='owner_user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auctions.user'),
            preserve_default=False,
        ),
    ]
