# Generated by Django 3.1.6 on 2021-02-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
