# Generated by Django 3.1.6 on 2021-03-21 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_follower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='follower',
            name='following',
        ),
        migrations.AddField(
            model_name='follower',
            name='follower',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='following', to='network.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='follower',
            name='user',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='network.user'),
            preserve_default=False,
        ),
    ]
