# Generated by Django 3.1.6 on 2021-04-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_auto_20210405_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(null=True, upload_to='static/capstone/images/%Y/%m/%d/'),
        ),
    ]
