# Generated by Django 3.1.6 on 2021-04-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0004_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(null=True, upload_to='capstone/static/capstone/images/'),
        ),
    ]
