# Generated by Django 3.1.6 on 2021-04-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0005_auto_20210406_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='recipes',
            field=models.ManyToManyField(blank=True, related_name='files', to='capstone.Recipe'),
        ),
    ]
