# Generated by Django 3.1.6 on 2021-04-07 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0006_file_recipes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='recipes',
        ),
    ]
