# Generated by Django 3.1.6 on 2021-04-07 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0007_remove_file_recipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='capstone.recipe'),
        ),
    ]
